### ISSUE TITLE
[BUG] Password is not saved correctly after some time

### ISSUE THREAD

**Issue by Aida-Enna** [ValvePython/steamctl#71]
**Description**
After some time, the password is forgotten in the credentials. The password argument created via #56 seems to be ignored when this happens. May be related to the original bug that caused me to ask for the feature.

**Steps to Reproduce the behavior**
Use the password argument and/or save the credentials and try again after a few weeks.

**What actually happend**
```
root@fordy:~# steamctl --user RandomUsername1 --password AwesomePassword2 depot info -a 1056640 -d 1056641
[INFO] Enter credentials for: RandomUsername1
```

It completely ignored the password flag (but supports it), you can see so when I attempted to use one line instead of two just to be sure.
```
root@fordy:~# steamctl --user RandomUsername1 -password AwesomePassword2 depot info -a 1056640 -d 1056641
usage: steamctl [-h] [--version] [--versions-report] [-l {quiet,info,debug}] [--anonymous] [--user USER]
                [--password PASSWORD]
                <command> ...
steamctl: error: argument <command>: invalid choice: 'AwesomePassword2' (choose from 'apps', 'assistant', 'authenticator', 'clear', 'cloud', 'depot', 'hlmaster', 'steamid', 'ugc', 'webapi', 'workshop')
```

Once I entered the correct password then it worked again, using the remembered credentials every time after.

**Logs**
<details><summary>steamctl -l debug</summary>
(Include logs related ot the issue. Use `steamctl -l debug` to get detailed log)
```
I was not aware of this command and will get logs next time.
```
</details>

**Versions Report**
<details><summary>steamctl --versions-report</summary>
(Run steamctl --versions-report and paste the output below)

```yaml
steamctl: 0.9.5

Dependencies:
               steam: 1.4.3
             appdirs: 1.4.4
         argcomplete: 2.0.0
                tqdm: 4.64.0
               arrow: 1.2.2
            pyqrcode: 1.2.1
      beautifulsoup4: 4.7.1
                 vpk: 1.4.0
                 vdf: 3.4
 gevent-eventemitter: 2.1
              gevent: 21.12.0
            greenlet: 1.1.2
              pyyaml: Not Installed
       pycryptodomex: 3.15.0
            protobuf: 3.14.0

Python runtime:
          executable: /usr/bin/python3.8
             version: 3.8.3 (default, May 14 2020, 22:09:32) [GCC 5.4.0 20160609]
            platform: linux

System info:
              system: Linux
             machine: x86_64
             release: 4.19-ovh-xxxx-std-ipv6-64
             version: #1273469 SMP Wed Jun 3 08:31:49 UTC 2020
```
</details>
